name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: |
          echo "Logging in to Docker Hub..."
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: onegymsolution.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t cygnetops/react-test -t onegymsolution.azurecr.io/myapp:${{ github.sha }} -f Dockerfile.dev .

      - name: Push Docker image to Docker Hub
        run: |
          echo "Pushing Docker image to Docker Hub..."
          docker push cygnetops/react-test

      - name: Push Docker image to ACR
        run: |
          echo "Pushing Docker image to ACR..."
          docker push onegymsolution.azurecr.io/myapp:${{ github.sha }}

      - name: Run tests
        run: |
          echo "Running tests..."
          docker run -e CI=true cygnetops/react-test npm test

      - name: Generate deployment package
        run: |
          echo "Generating deployment package..."
          zip -r deploy.zip . -x '*.git*'

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: OneGymSolution
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: deploy.zip