name: PR_Request
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: |
       echo "Installing dependencies..."
       npm install

    - name: Test  
      run: |
        echo "Run Test Cases..."
        npm run test